# fly.toml app configuration file generated for mobnator-backend on 2023-10-15T14:48:32-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mobnator-backend"
primary_region = "gig"

[build]

[http_service]
  internal_port = 5004
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
