name: Create Website Docker Images

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Version tag"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build_mobnator_website
        uses: docker/build-push-action@v6
        with:
          context: ./frontend/
          # Only push if on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/fraidev/mobnator_website:latest
            ghcr.io/fraidev/mobnator_website:${{ github.event.inputs.version }}
